import SearchBar from "../components/dashboard/SearchBar";
import SectionTitle from "../components/common/SectionTitle";
import CompanyCard from "../components/dashboard/CompanyCard";
import FinancialCard from "../components/dashboard/FinancialCard";
import NewsCard from "../components/dashboard/NewsCard";
import RecommendationCard from "../components/dashboard/RecommendationCard";
import { useState } from "react";
import { useResearch } from "../hooks/useResearch";
import Timeline from "../components/dashboard/Timeline";
import { useTimeline } from "../hooks/useTimeline";
function Home() {
  const [company, setCompany] = useState("");
  const { analysis, loading, error, analyzeCompany } = useResearch();
  const { events, clearTimeline } = useTimeline();
  const handleAnalyze = () => {
    if (!company.trim()) return;
    clearTimeline();
    analyzeCompany(company);
  };

  return (
    <main className="min-h-screen bg-[#0A0E13]">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=Inter:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap');
        body { font-family: 'Inter', sans-serif; }
      `}</style>

      <section className="mx-auto flex max-w-6xl flex-col items-center px-6 py-24 text-center">
        <span className="flex items-center gap-2 rounded-full border border-[#212B35] bg-[#10161D] px-4 py-1.5 font-mono text-[11px] uppercase tracking-[0.2em] text-[#7C93F5]">
          <span className="h-1.5 w-1.5 rounded-full bg-[#2FD180]" />
          Sys // Ready — AI Research Engine
        </span>

        <h1
          style={{ fontFamily: "'Space Grotesk', sans-serif" }}
          className="mt-6 text-5xl font-bold tracking-tight text-[#E7ECF1]"
        >
          AI Investment Research Agent
        </h1>

        <p className="mt-6 max-w-2xl text-lg leading-8 text-[#8A99A8]">
          Research any public company using AI. Analyze financials, latest
          news, business risks, and receive an investment recommendation with
          detailed reasoning.
        </p>

        {error && (
          <p className="mt-4 font-mono text-sm text-[#F2596B]">
            ERROR — {error}
          </p>
        )}

        <div className="mt-12 w-full max-w-3xl">
          <SearchBar
            company={company}
            setCompany={setCompany}
            onAnalyze={handleAnalyze}
            loading={loading}
          />
        </div>
      </section>

      <div className="mx-auto mt-10 max-w-6xl px-6">
    <Timeline events={events} />
</div>

      <section className="mx-auto max-w-6xl space-y-10 px-6 pb-24">
        <div>
          <SectionTitle
            index="01"
            total="04"
            title="Company Overview"
            subtitle="Basic information about the selected company"
          />
          <CompanyCard company={analysis?.company} />
        </div>

        <div>
          <SectionTitle
            index="02"
            total="04"
            title="Financial Health"
            subtitle="Key financial metrics and performance"
          />
          <FinancialCard market={analysis?.market} />
        </div>

        <div>
          <SectionTitle
            index="03"
            total="04"
            title="Latest News"
            subtitle="Recent developments affecting the company"
          />
          <NewsCard news={analysis?.news} />
        </div>

        <div>
          <SectionTitle
            index="04"
            total="04"
            title="Investment Recommendation"
            subtitle="Final decision generated by the AI agent"
          />
          <RecommendationCard analysis={analysis?.analysis} />
        </div>
      </section>
    </main>
  );
}

export default Home;