import SearchBar from "../components/dashboard/SearchBar";
import SectionTitle from "../components/common/SectionTitle";
import CompanyCard from "../components/dashboard/CompanyCard";
import FinancialCard from "../components/dashboard/FinancialCard";
import NewsCard from "../components/dashboard/NewsCard";
import RecommendationCard from "../components/dashboard/RecommendationCard";
import { useState } from "react";
import { useResearch } from "../hooks/useResearch";
function Home() {

  const [company , setCompany] = useState("");
  const{analysis , loading , error , analyzeCompany} = useResearch();

  const handleAnalyze= () => {
    if(!company.trim()) return ;
    analyzeCompany(company);
  }
  return (
    <main className="min-h-screen bg-slate-50">
      <section className="mx-auto flex max-w-6xl flex-col items-center px-6 py-24 text-center">
        <span className="rounded-full bg-blue-100 px-4 py-2 text-sm font-semibold text-blue-700">
          AI Powered Investment Research
        </span>

        <h1 className="mt-6 text-5xl font-bold tracking-tight text-slate-900">
          AI Investment Research Agent
        </h1>

        <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">
          Research any public company using AI. Analyze financials, latest
          news, business risks, and receive an investment recommendation with
          detailed reasoning.
        </p>

        <div className="mt-12 w-full max-w-3xl">
          <SearchBar  company={company}
          setCompany={setCompany}
          onAnalyze={handleAnalyze}
          loading={loading}
          />
        </div>
      </section>

      <section className="mx-auto max-w-6xl space-y-8 px-6 pb-24">

  <div>
    <SectionTitle
      title="Company Overview"
      subtitle="Basic information about the selected company"
    />
    <CompanyCard company={analysis?.company}/>
  </div>

  <div>
    <SectionTitle
      title="Financial Health"
      subtitle="Key financial metrics and performance"
    />
    <FinancialCard market={analysis?.market} />
  </div>

  <div>
    <SectionTitle
      title="Latest News"
      subtitle="Recent developments affecting the company"
    />
    <NewsCard news={analysis?.news} />
  </div>


  <div>
    <SectionTitle
      title="Investment Recommendation"
      subtitle="Final decision generated by the AI agent"
    />
    <RecommendationCard analysis={analysis?.analysis}/>
  </div>

</section>
    </main>
  );
}

export default Home;